### ISSUE TITLE
App validation using file extension?

### ISSUE THREAD

**Issue by swaps19** [icyleaf/app_info#1]
Is it necessary to validate a file if its an `app` or not just by looking at its extension? I can have a temp file to be parsed which is not having a `.ipa`/`.apk` extension.
The same case can be a vice-versa; if I have a file with `.ipa`/`.apk` extension but actual content is different.

**Comment by icyleaf** [comment]
It is gentleman's agreement, such like mime type. i do not think this is a big problem. PL is welcome if you want do it and make it smart.
