### ISSUE TITLE
CFBundleDisplayName can't handle UTF-8

### ISSUE THREAD

**Issue by MobilEKG** [icyleaf/app_info#11]
when CFBundleDisplayName is NOT English, ipa.info[:CFBundleDisplayName] failed:

 [!] undefined method `[]' for #<AppInfo::Parser::InfoPlist:0x00007fcc01131e90> (NoMethodError)
	from /private/var/root/project/iOS/fastlane-kit/GeneralFastfile.rb:16:in `chdir'
	from /private/var/root/project/iOS/fastlane-kit/GeneralFastfile.rb:16:in `get_ipa_info'
	from Fastfile:202:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by icyleaf** [comment]
Sorry, i wrote incorrect usage, for your case, you can call `ipa.info.display_name` etc which i was [wrapped ones](https://github.com/icyleaf/app_info/blob/master/lib/app_info/parser/ipa/info_plist.rb#L29). Anyway if you want call unwrapped key, try `ipa.info.info['CFBundleDisplayName']`(no symbol key accepted). i will solve in next version. 

Thanks for feedback.

**Comment by icyleaf** [comment]
Fixed and released v1.1.1

**Comment by icyleaf** [comment]
Fixed and released v1.1.2

**Comment by icyleaf** [comment]
Reopen if any issues
