### ISSUE TITLE
不支持苹果M1芯片？

### ISSUE THREAD

**Issue by DreamPWJ** [icyleaf/app_info#28]
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/pngdefry-0.1.3/lib/pngdefry.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/pngdefry-0.1.3/lib/pngdefry.bundle - /Library/Ruby/Gems/2.6.0/gems/pngdefry-0.1.3/lib/pngdefry.bundle (LoadError)

**Comment by DreamPWJ** [comment]
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

**Comment by DreamPWJ** [comment]
fastlane-plugin-app_info  也不行 
![image](https://user-images.githubusercontent.com/16730031/113548926-0497a180-9623-11eb-9e98-9a336f3c3131.png)

**Comment by DreamPWJ** [comment]
@icyleaf 帮忙看看，现在特别需要这个app info返回的信息以及您开源的多渠道的，多渠道和加固混淆的还没有试，试了第一个就不行

**Comment by icyleaf** [comment]
app_info 依赖 pngdefry 来做 iOS png 图片的解密，不确定是否支持 M1 芯片，明天上班我来看看

**Comment by DreamPWJ** [comment]
@icyleaf 感谢，您的其它插件也非常好，但是我还没去尝试，最近在尝试fastlane生态，现在多渠道打包不知道好用不，多渠道和加固必须都是未签名的apk包吗？

**Comment by icyleaf** [comment]
目前 [pngdefry]() 很久没有更新可能需要给他提 PR 或者更换其他方案，如果着急你可以使用这样的方式使用：

```ruby
# 使用 bundle 安装
arch -arch x86_64 bundle install
# 执行命令
arch -arch x86_64 bundle exec fastlane [lane]
```

上面方法应该可用，我身边尚未有 M1 的电脑暂时无法测试，希望临时可以帮助到你。

**Comment by DreamPWJ** [comment]
@icyleaf 依然不行  现在暂时使用fastlane提供的get_ipa_info_plist_value可以获取我想要的信息，但是android还是不知道如何获取app应用名称，其他版本等都能获取

**Comment by icyleaf** [comment]
app

**Comment by DreamPWJ** [comment]
@icyleaf 是可以了 但是ios获取的Name不对  android是对的

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/113737605-c25c8600-9730-11eb-83ed-e8c7e0e06a4a.png)

**Comment by icyleaf** [comment]
这个是 fastlane-plugin-app_info 的 bug 已修复，请升级 04.1

**Comment by DreamPWJ** [comment]
感谢 我昨天也已通过其他方式兼容了这个bug

**Comment by DreamPWJ** [comment]
@icyleaf  有两个疑问 1. 现在获取信息可能需要5秒左右有点慢 希望是1秒解决  2. 对于获取信息是否做了拆包操作，对包有影响吗？

**Comment by icyleaf** [comment]
> 2. 对于获取信息是否做了拆包操作，对包有影响吗？

是的，不会对原包有任何写操作。

> 1. 现在获取信息可能需要5秒左右有点慢 希望是1秒解决

解决不了，iOS 是直接把 ipa 解压缩到了临时目录，Android 因为用的第三方库它只能基于内存读取，有必要我都会解压到临时目录。
