### ISSUE TITLE
不支持Flutter项目？

### ISSUE THREAD

**Issue by DreamPWJ** [icyleaf/app_info#29]
![image](https://user-images.githubusercontent.com/16730031/114819232-bab37600-9def-11eb-8232-521fa3724f6f.png)

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/114820106-13374300-9df1-11eb-9cd4-ea2fffd09581.png)
ios项目可以， flutter同时打android和ios包， android获取版本信息失败，我感觉是因为包不在android工程目录下，而ios的包在ios工程目录下

**Comment by DreamPWJ** [comment]
难道需要我复制一个包到android目录下 只为解析信息？

**Comment by icyleaf** [comment]
没有做过 flutter，请问 flutter 的输出目录在哪里？

**Comment by icyleaf** [comment]
而且这个大概率是 fastlane-plugin-app_info 的问题，请在那边提 issue 😆

**Comment by DreamPWJ** [comment]
是的 fastlane-plugin-app_info 的  指定了包路径了  就是因为包在的路径不是工程路径   输出在根目录build/app/outputs/apk   zai在android工程外面
![image](https://user-images.githubusercontent.com/16730031/114837032-d6c21200-9e05-11eb-9395-b03fbe25f917.png)

**Comment by icyleaf** [comment]
这个不属于 bug，自定义的项目用自定义的路径

**Comment by DreamPWJ** [comment]
自定义了啊，因为不在工程目录报错啊  您可以测试一下

**Comment by DreamPWJ** [comment]
我感觉android解析不只是需要apk包  还依赖android工程目录的相关文件@icyleaf

**Comment by icyleaf** [comment]
我找了一个 flutter 的 apk 貌似有些线索了，能把你第一个图中 `fastlane finished with errors` 后面以文本的形式粘贴过来吗？

**Comment by DreamPWJ** [comment]
重新复现了异常 @icyleaf `18:23:09  +-------------------------------------------+---------+---------------------------------------------+
18:23:09  |                                           Used plugins                                            |
18:23:09  +-------------------------------------------+---------+---------------------------------------------+
18:23:09  | Plugin                                    | Version | Action                                      |
18:23:09  +-------------------------------------------+---------+---------------------------------------------+
18:23:09  | fastlane-plugin-huawei_appgallery_connect | 1.0.15  | huawei_appgallery_connect_submit_for_review |
18:23:09  |                                           |         | huawei_appgallery_connect                   |
18:23:09  |                                           |         | huawei_appgallery_connect_get_app_info      |
18:23:09  | fastlane-plugin-fir_cli                   | 2.0.12  | fir_cli                                     |
18:23:09  | fastlane-plugin-versioning_android        | 0.1.0   | android_get_version_name                    |
18:23:09  |                                           |         | android_set_version_code                    |
18:23:09  |                                           |         | android_set_version_name                    |
18:23:09  |                                           |         | android_get_version_code                    |
18:23:09  | fastlane-plugin-badge                     | 1.5.0   | add_badge                                   |
18:23:09  | fastlane-plugin-app_info                  | 0.4.1   | app_info                                    |
18:23:09  +-------------------------------------------+---------+---------------------------------------------+
18:23:09  
18:23:09  [18:23:09]: ------------------------------
18:23:09  [18:23:09]: --- Step: default_platform ---
18:23:09  [18:23:09]: ------------------------------
18:23:09  [18:23:09]: Driving the lane 'get_app_info' 🚀
18:23:09  [18:23:09]: 获取App信息
18:23:09  
18:23:09  [18:23:09]: ----------------------
18:23:09  [18:23:09]: --- Step: app_info ---
18:23:09  [18:23:09]: ----------------------
18:23:09  +------------------+--------------+
18:23:09  |          Lane Context           |
18:23:09  +------------------+--------------+
18:23:09  | DEFAULT_PLATFORM | android      |
18:23:09  | PLATFORM_NAME    |              |
18:23:09  | LANE_NAME        | get_app_info |
18:23:09  +------------------+--------------+
18:23:09  [18:23:09]: Android::NotFoundError
18:23:09  
18:23:09  +------+------------------+-------------+
18:23:09  |           fastlane summary            |
18:23:09  +------+------------------+-------------+
18:23:09  | Step | Action           | Time (in s) |
18:23:09  +------+------------------+-------------+
18:23:09  | 1    | default_platform | 0           |
18:23:09  | 💥   | app_info         | 0           |
18:23:09  +------+------------------+-------------+
18:23:09  
18:23:09  [18:23:09]: fastlane finished with errors
18:23:09  
18:23:09  Looking for related GitHub issues on fastlane/fastlane...
18:23:09  
18:23:10  Found no similar issues. To create a new issue, please visit:
18:23:10  https://github.com/fastlane/fastlane/issues/new
18:23:10  Run `fastlane env` to append the fastlane environment to your issue
18:23:10  /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:196:in `res_hex_id': [!] Android::NotFoundError (Android::NotFoundError)
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:175:in `strid2int'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:131:in `find'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:481:in `find'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/app-info-2.4.3/lib/app_info/apk.rb:51:in `name'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:42:in `block in common_columns'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:40:in `each'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:40:in `each_with_object'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:40:in `common_columns'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:36:in `table_columns'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:27:in `print_table!'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:17:in `run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
18:23:10  	from ../GeneralFastfile:35:in `block in parsing_binding'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/lane.rb:33:in `call'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
18:23:10  	from /usr/local/bin/fastlane:23:in `load'
18:23:10  	from /usr/local/bin/fastlane:23:in `<main>'
18:23:10  /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:196:in `res_hex_id': Android::NotFoundError (Android::NotFoundError)
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:175:in `strid2int'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:131:in `find'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/resource.rb:481:in `find'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/app-info-2.4.3/lib/app_info/apk.rb:51:in `name'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:42:in `block in common_columns'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:40:in `each'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:40:in `each_with_object'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:40:in `common_columns'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:36:in `table_columns'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:27:in `print_table!'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.1/lib/fastlane/plugin/app_info/actions/app_info_action.rb:17:in `run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
18:23:10  	from ../GeneralFastfile:35:in `block in parsing_binding'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/lane.rb:33:in `call'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
18:23:10  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
18:23:10  	from /usr/local/bin/fastlane:23:in `load'
18:23:10  	from /usr/local/bin/fastlane:23:in `<main>'`

**Comment by icyleaf** [comment]
那就是我发现的问题，感谢反馈。已经更新新版本麻烦在帮忙测试看看

**Comment by DreamPWJ** [comment]
@icyleaf 可以了 谢谢了

**Comment by DreamPWJ** [comment]
@icyleaf 可以了 谢谢了
