### ISSUE TITLE
 incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by DreamPWJ** [icyleaf/app_info#31]
/Library/Ruby/Gems/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `join': [!] incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError) @icyleaf

**Comment by DreamPWJ** [comment]
10:51:38  🔗  You can ⌘ + double-click on links to open them directly in your browser.
10:51:38  /Library/Ruby/Gems/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `join': [!] incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `render'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:31:in `puts'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:31:in `puts'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:31:in `print_table!'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:17:in `run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
10:51:38  	from ../GeneralFastfile:35:in `block in parsing_binding'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane.rb:33:in `call'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
10:51:38  	from /usr/local/bin/fastlane:23:in `load'
10:51:38  	from /usr/local/bin/fastlane:23:in `<main>'
10:51:38  /Library/Ruby/Gems/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `render'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:31:in `puts'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:31:in `puts'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:31:in `print_table!'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-app_info-0.4.2/lib/fastlane/plugin/app_info/actions/app_info_action.rb:17:in `run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
10:51:38  	from ../GeneralFastfile:35:in `block in parsing_binding'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane.rb:33:in `call'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
10:51:38  	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
10:51:38  	from /usr/local/bin/fastlane:23:in `load'
10:51:38  	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by icyleaf** [comment]
Please file it in [fastlane-plugin-app_info](https://github.com/icyleaf/fastlane-plugin-app_info).

**Comment by DreamPWJ** [comment]
之前都是好的，今天只有ios会有这个问题 ，  我已经暂时用get_ipa_info_plist_value重新实现了一个app info

**Comment by icyleaf** [comment]
我猜测是 fastlane 依赖的 terminal-table 版本的问题

**Comment by DreamPWJ** [comment]
版本都没变过，突然就不行了

**Comment by icyleaf** [comment]
还有一种可能是 app 某些字段的文字字符集不是 UTF-8 and ASCII-8BIT 的

**Comment by DreamPWJ** [comment]
> 还有一种可能是 app 某些字段的文字字符集不是 UTF-8 and ASCII-8BIT 的

应该不是代码的问题，多个ios项目同时出现这个问题，但是环境也没动

**Comment by icyleaf** [comment]
多个ios项目具体是指？

**Comment by DreamPWJ** [comment]
> 多个ios项目具体是指？

反正不是代码的问题，就是多个ios工程代码同时出现这个问题， 好多功能都没有提交代码

**Comment by icyleaf** [comment]
问题找到了，是 ipa adhoc 包新的签名方式变了，导致新增了一个 `DER-Encoded-Profile` 的键值，他是一个二进制文件流无法解析造成的。
