### ISSUE TITLE
Cannot read mobileprovision on Ubuntu 18.04

### ISSUE THREAD

**Issue by FEApaydin** [icyleaf/app_info#4]
The mobileprovision file reading doesn't seem to work on Ubuntu 18.04 servers.

I have tried following commands:

```ruby
ipa=AppInfo.parse("tmp/storage/ios/app.ipa") # <AppInfo::Parser::IPA:0x005593c7258108 @file="tmp/storage/ios/app.ipa", @contents="/tmp/d20190628-1205-1l8tcbk/AppInfo-ios-571df9d7d57eb92000ae58c3a9659007", @app_path="/tmp/d20190628-1205-1l8tcbk/AppInfo-ios-571df9d7d57eb92000ae58c3a9659007/Payload/AppName.app">
ipa.expired_date # nil
ipa.mobileprovision # <AppInfo::Parser::MobileProvision:0x00558c5c7d4c20 @path=nil>
```

I also tried to work directly on embedded.mobileprovision file, but it didn't work as well.

```ruby
p=AppInfo.parse("/tmp/embedded.mobileprovision") # <AppInfo::Parser::MobileProvision:0x005578ab330df0 @path="/tmp/embedded.mobileprovision">
p.expired_date # nil
p.team_name # nil
```

The same IPA file and same methods gives output for `ipa.expired_date` on MacOS.

**Comment by icyleaf** [comment]
Parse mobileprovision file require macOS. https://github.com/icyleaf/app_info/blob/master/spec/app_info/parser/ipa/mobile_provision_spec.rb#L6
