### ISSUE TITLE
rails 5.2.3 ios app parsing release type set to nil

### ISSUE THREAD

**Issue by junipdewan** [icyleaf/app_info#5]

**Comment by icyleaf** [comment]
Please make sure parse iOS file with macOS OS.

**Comment by junipdewan** [comment]
[Files.zip](https://github.com/icyleaf/app_info/files/3344952/Files.zip)
Here I have uploaded the Info.plist file.

**Comment by icyleaf** [comment]
File was verified and parsed works. i triggered a build and passed in Ubuntu. https://travis-ci.org/icyleaf/app_info/jobs/552699315.

**Comment by junipdewan** [comment]
Hey thanks for giving immediate response , it was working on version 1.0.1 and when i upgrade the gem to latest version then it is breaking giving release type as nil.There may be issue on my side also.
let me check and will get back to you

**Comment by icyleaf** [comment]
Hi @junipdewan, is it solve the issue?

**Comment by junipdewan** [comment]
@icyleaf, Yes it is working, closing the issue
